<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\CAManagement.X509\CAManagement.X509.csproj" />
        <ProjectReference Include="..\CAManagement.Pkcs11\CAManagement.Pkcs11.csproj" />
    </ItemGroup>

</Project>
